<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { FileDown, FileUp, Landmark, Plus } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import type { ApiResponse, Company, Paginated, Receivable } from '../types'
import PageHeader from '../components/PageHeader.vue'
import ModalDialog from '../components/ModalDialog.vue'

interface Account{id:string;company_id:string;bank_code:string;bank_name:string;branch:string;account:string;account_digit?:string;is_default:boolean}
interface Agreement{id:string;company_id:string;bank_account_id:string;name:string;provider:string;environment:string;agreement_number?:string;wallet?:string;cnab_layout:string;is_active:boolean}
const accounts=ref<Account[]>([]);const agreements=ref<Agreement[]>([]);const companies=ref<Company[]>([]);const receivables=ref<Receivable[]>([]);const returnCompanyId=ref('');const error=ref('');const result=ref('');const accountModal=ref(false);const agreementModal=ref(false);const cnabModal=ref(false)
const accountForm=reactive({company_id:'',bank_code:'001',bank_name:'Banco do Brasil',branch:'',branch_digit:'',account:'',account_digit:'',account_type:'CHECKING',pix_key_type:'',pix_key:'',is_default:true})
const agreementForm=reactive({company_id:'',bank_account_id:'',name:'Convênio de cobrança',provider:'SANDBOX',environment:'SANDBOX',agreement_number:'',wallet:'',beneficiary_code:'',cnab_layout:'240',settings:{},credentials:{}})
const cnabForm=reactive({bank_agreement_id:'',receivable_ids:[] as string[]})
const companyName=(id:string)=>companies.value.find(x=>x.id===id)?.trade_name||companies.value.find(x=>x.id===id)?.legal_name||id
const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
async function load(){try{const [a,b,c,d]=await Promise.all([api.get<ApiResponse<Account[]>>('/v1/bank-accounts'),api.get<ApiResponse<Agreement[]>>('/v1/bank-agreements'),api.get<ApiResponse<Company[]>>('/v1/companies'),api.get<Paginated<Receivable>>('/v1/receivables',{params:{per_page:100}})]);accounts.value=a.data.data;agreements.value=b.data.data;companies.value=c.data.data;receivables.value=d.data.data;if(!accountForm.company_id&&companies.value[0])accountForm.company_id=companies.value[0].id;if(!agreementForm.company_id&&companies.value[0])agreementForm.company_id=companies.value[0].id;if(!returnCompanyId.value&&companies.value[0])returnCompanyId.value=companies.value[0].id}catch(e){error.value=apiError(e)}}
async function createAccount(){try{await api.post('/v1/bank-accounts',accountForm);accountModal.value=false;await load()}catch(e){error.value=apiError(e)}}
async function createAgreement(){try{await api.post('/v1/bank-agreements',agreementForm);agreementModal.value=false;await load()}catch(e){error.value=apiError(e)}}
async function generateCnab(){try{const r=await api.post<ApiResponse<{download_url:string;object_key:string;sha256:string}>>('/v1/cnab/remittances',cnabForm);result.value=`Remessa gerada: ${r.data.data.object_key}\nSHA-256: ${r.data.data.sha256}\nDownload: ${r.data.data.download_url}`;cnabModal.value=false}catch(e){error.value=apiError(e)}}
async function importReturn(event:Event){const input=event.target as HTMLInputElement;if(!input.files?.[0])return;const data=new FormData();data.append('file',input.files[0]);try{const r=await api.post<ApiResponse<Record<string,unknown>>>(`/v1/cnab/returns?company_id=${encodeURIComponent(returnCompanyId.value)}`,data,{headers:{'Content-Type':'multipart/form-data'}});result.value=`Retorno processado: ${JSON.stringify(r.data.data,null,2)}`;await load()}catch(e){error.value=apiError(e)}finally{input.value=''}}
onMounted(load)
</script>
<template><PageHeader title="Bancos e CNAB" subtitle="Contas, convênios, remessas e retornos bancários."><select v-model="returnCompanyId" class="select max-w-64" aria-label="Empresa do retorno CNAB"><option v-for="c in companies" :key="c.id" :value="c.id">{{c.trade_name||c.legal_name}}</option></select><label class="btn-secondary cursor-pointer" :class="!returnCompanyId && 'pointer-events-none opacity-50'"><FileUp :size="18"/> Importar retorno<input type="file" class="hidden" accept=".ret,.txt" :disabled="!returnCompanyId" @change="importReturn"/></label><button class="btn-secondary" @click="cnabModal=true"><FileDown :size="18"/> Gerar remessa</button><button class="btn-secondary" @click="agreementModal=true"><Plus :size="18"/> Convênio</button><button class="btn-primary" @click="accountModal=true"><Plus :size="18"/> Conta bancária</button></PageHeader><p v-if="error" class="mb-5 rounded-xl bg-rose-50 p-3 text-rose-700">{{error}}</p><pre v-if="result" class="mb-5 whitespace-pre-wrap rounded-xl bg-slate-900 p-4 text-xs text-emerald-300">{{result}}</pre><div class="grid gap-6 lg:grid-cols-2"><section><h2 class="mb-3 text-lg font-semibold">Contas bancárias</h2><div class="space-y-3"><article v-for="item in accounts" :key="item.id" class="card flex items-center gap-3"><div class="rounded-xl bg-blue-50 p-3 text-blue-700"><Landmark :size="22"/></div><div><p class="font-semibold">{{item.bank_code}} · {{item.bank_name}}</p><p class="text-sm text-slate-500">Ag. {{item.branch}} · Conta {{item.account}}-{{item.account_digit}}</p><p class="text-xs text-slate-400">{{companyName(item.company_id)}}</p></div><span v-if="item.is_default" class="badge ml-auto bg-teal-100 text-teal-700">Padrão</span></article><p v-if="!accounts.length" class="card text-center text-slate-400">Nenhuma conta.</p></div></section><section><h2 class="mb-3 text-lg font-semibold">Convênios</h2><div class="space-y-3"><article v-for="item in agreements" :key="item.id" class="card"><div class="flex items-start justify-between"><div><p class="font-semibold">{{item.name}}</p><p class="text-sm text-slate-500">{{item.provider}} · {{item.environment}}</p><p class="mt-2 text-xs text-slate-400">Convênio {{item.agreement_number||'—'}} · Carteira {{item.wallet||'—'}} · CNAB {{item.cnab_layout}}</p></div><span class="badge bg-emerald-100 text-emerald-700">Ativo</span></div></article><p v-if="!agreements.length" class="card text-center text-slate-400">Nenhum convênio.</p></div></section></div>
<ModalDialog :open="accountModal" title="Cadastrar conta bancária" size="lg" @close="accountModal=false"><form class="grid gap-4 md:grid-cols-2" @submit.prevent="createAccount"><div class="md:col-span-2"><label class="label">Empresa</label><select v-model="accountForm.company_id" class="select"><option v-for="c in companies" :key="c.id" :value="c.id">{{c.trade_name||c.legal_name}}</option></select></div><div><label class="label">Código banco</label><input v-model="accountForm.bank_code" maxlength="3" class="input" required/></div><div><label class="label">Nome banco</label><input v-model="accountForm.bank_name" class="input" required/></div><div><label class="label">Agência</label><input v-model="accountForm.branch" class="input" required/></div><div><label class="label">Dígito agência</label><input v-model="accountForm.branch_digit" class="input"/></div><div><label class="label">Conta</label><input v-model="accountForm.account" class="input" required/></div><div><label class="label">Dígito conta</label><input v-model="accountForm.account_digit" class="input"/></div><div><label class="label">Tipo chave PIX</label><select v-model="accountForm.pix_key_type" class="select"><option value="">Sem chave</option><option>CNPJ</option><option>EMAIL</option><option>PHONE</option><option>EVP</option></select></div><div><label class="label">Chave PIX</label><input v-model="accountForm.pix_key" class="input"/></div><label class="md:col-span-2 flex gap-2 text-sm"><input v-model="accountForm.is_default" type="checkbox"/> Conta padrão da empresa</label><div class="md:col-span-2 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="accountModal=false">Cancelar</button><button class="btn-primary">Salvar</button></div></form></ModalDialog>
<ModalDialog :open="agreementModal" title="Cadastrar convênio bancário" size="lg" @close="agreementModal=false"><form class="grid gap-4 md:grid-cols-2" @submit.prevent="createAgreement"><div><label class="label">Empresa</label><select v-model="agreementForm.company_id" class="select"><option v-for="c in companies" :key="c.id" :value="c.id">{{c.trade_name||c.legal_name}}</option></select></div><div><label class="label">Conta</label><select v-model="agreementForm.bank_account_id" class="select" required><option value="" disabled>Selecione</option><option v-for="a in accounts.filter(x=>x.company_id===agreementForm.company_id)" :key="a.id" :value="a.id">{{a.bank_name}} · {{a.account}}</option></select></div><div><label class="label">Nome</label><input v-model="agreementForm.name" class="input" required/></div><div><label class="label">Provider</label><select v-model="agreementForm.provider" class="select"><option>SANDBOX</option><option>BANCO_DO_BRASIL</option><option>ITAU</option><option>SICOOB</option><option>SICREDI</option></select></div><div><label class="label">Ambiente</label><select v-model="agreementForm.environment" class="select"><option>SANDBOX</option><option>HOMOLOGATION</option><option>PRODUCTION</option></select></div><div><label class="label">Layout</label><select v-model="agreementForm.cnab_layout" class="select"><option>240</option><option>400</option></select></div><div><label class="label">Número convênio</label><input v-model="agreementForm.agreement_number" class="input"/></div><div><label class="label">Carteira</label><input v-model="agreementForm.wallet" class="input"/></div><div><label class="label">Código beneficiário</label><input v-model="agreementForm.beneficiary_code" class="input"/></div><div class="md:col-span-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Credenciais reais devem ser cadastradas pela API/Secret Manager durante a homologação do banco. O provider SANDBOX funciona imediatamente.</div><div class="md:col-span-2 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="agreementModal=false">Cancelar</button><button class="btn-primary">Salvar</button></div></form></ModalDialog>
<ModalDialog :open="cnabModal" title="Gerar remessa CNAB 240" size="lg" @close="cnabModal=false"><form class="space-y-4" @submit.prevent="generateCnab"><div><label class="label">Convênio</label><select v-model="cnabForm.bank_agreement_id" class="select" required><option value="" disabled>Selecione</option><option v-for="a in agreements" :key="a.id" :value="a.id">{{a.name}} · {{a.provider}}</option></select></div><div><label class="label">Títulos</label><div class="max-h-64 space-y-2 overflow-auto rounded-xl border border-slate-200 p-3"><label v-for="r in receivables.filter(x=>['OPEN','REGISTERED'].includes(x.status))" :key="r.id" class="flex items-center gap-3 rounded-lg p-2 hover:bg-slate-50"><input v-model="cnabForm.receivable_ids" type="checkbox" :value="r.id"/><span class="flex-1 text-sm">{{r.document_number}}</span><span class="text-sm font-semibold">{{money(r.balance)}}</span></label></div></div><div class="flex justify-end gap-2"><button type="button" class="btn-secondary" @click="cnabModal=false">Cancelar</button><button class="btn-primary" :disabled="!cnabForm.receivable_ids.length">Gerar arquivo</button></div></form></ModalDialog></template>
