<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Check, Clipboard, HandCoins, Plus } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import type { ApiResponse, Charge, Paginated, Receivable } from '../types'
import PageHeader from '../components/PageHeader.vue'
import ModalDialog from '../components/ModalDialog.vue'
import StatusBadge from '../components/StatusBadge.vue'

interface Payment{id:string;receivable_id:string;provider:string;external_id:string;amount:string;paid_at:string;payment_method:string;status:string}
const charges=ref<Charge[]>([]);const payments=ref<Payment[]>([]);const receivables=ref<Receivable[]>([]);const error=ref('');const modal=ref(false);const copied=ref('')
const form=reactive({receivable_id:'',charge_id:null as string|null,provider:'MANUAL',external_id:'',end_to_end_id:'',amount:'0.00',paid_at:new Date().toISOString().slice(0,16),payment_method:'TRANSFER'})
const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
async function load(){try{const [a,b,c]=await Promise.all([api.get<ApiResponse<Charge[]>>('/v1/charges'),api.get<ApiResponse<Payment[]>>('/v1/payments'),api.get<Paginated<Receivable>>('/v1/receivables',{params:{per_page:100}})]);charges.value=a.data.data;payments.value=b.data.data;receivables.value=c.data.data}catch(e){error.value=apiError(e)}}
async function pay(){try{await api.post('/v1/payments',{...form,paid_at:new Date(form.paid_at).toISOString(),charge_id:form.charge_id||null,end_to_end_id:form.end_to_end_id||null});modal.value=false;await load()}catch(e){error.value=apiError(e)}}
async function copy(value:string|undefined,key:string){if(!value)return;await navigator.clipboard.writeText(value);copied.value=key;setTimeout(()=>copied.value='',1500)}
onMounted(load)
</script>
<template><PageHeader title="Cobranças e pagamentos" subtitle="Boletos, PIX, liquidações e baixas financeiras."><button class="btn-primary" @click="modal=true"><Plus :size="18"/> Registrar pagamento</button></PageHeader><p v-if="error" class="mb-5 rounded-xl bg-rose-50 p-3 text-rose-700">{{error}}</p><section><h2 class="mb-3 text-lg font-semibold">Cobranças emitidas</h2><div class="table-wrap"><table class="table"><thead><tr><th>Provider</th><th>Identificadores</th><th>Linha digitável / PIX</th><th>Status</th></tr></thead><tbody><tr v-for="item in charges" :key="item.id"><td><p class="font-semibold">{{item.provider}}</p><p class="text-xs text-slate-400">{{item.charge_type}}</p></td><td><p class="text-xs">{{item.external_id}}</p><p class="text-xs text-slate-400">Nosso nº {{item.our_number||'—'}} · TXID {{item.txid||'—'}}</p></td><td class="max-w-md"><button v-if="item.digitable_line" class="mb-1 flex max-w-full items-center gap-2 text-left text-xs text-teal-700" @click="copy(item.digitable_line,item.id+'line')"><component :is="copied===item.id+'line'?Check:Clipboard" :size="14"/><span class="truncate">{{item.digitable_line}}</span></button><button v-if="item.pix_copy_paste" class="flex max-w-full items-center gap-2 text-left text-xs text-blue-700" @click="copy(item.pix_copy_paste,item.id+'pix')"><component :is="copied===item.id+'pix'?Check:Clipboard" :size="14"/><span class="truncate">PIX Copia e Cola</span></button></td><td><StatusBadge :status="item.status"/></td></tr><tr v-if="!charges.length"><td colspan="4" class="py-10 text-center text-slate-400">Nenhuma cobrança emitida.</td></tr></tbody></table></div></section><section class="mt-7"><h2 class="mb-3 text-lg font-semibold">Pagamentos</h2><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Provider</th><th>Referência</th><th>Valor</th><th>Status</th></tr></thead><tbody><tr v-for="item in payments" :key="item.id"><td>{{new Date(item.paid_at).toLocaleString('pt-BR')}}</td><td>{{item.provider}}<p class="text-xs text-slate-400">{{item.payment_method}}</p></td><td class="text-xs">{{item.external_id}}</td><td class="font-semibold">{{money(item.amount)}}</td><td><StatusBadge :status="item.status"/></td></tr><tr v-if="!payments.length"><td colspan="5" class="py-10 text-center text-slate-400">Nenhum pagamento registrado.</td></tr></tbody></table></div></section>
<ModalDialog :open="modal" title="Registrar pagamento manual" @close="modal=false"><form class="space-y-4" @submit.prevent="pay"><div><label class="label">Recebível</label><select v-model="form.receivable_id" class="select" required><option value="" disabled>Selecione</option><option v-for="r in receivables.filter(x=>Number(x.balance)>0)" :key="r.id" :value="r.id">{{r.document_number}} · {{money(r.balance)}}</option></select></div><div class="grid grid-cols-2 gap-3"><div><label class="label">Valor</label><input v-model="form.amount" type="number" min="0.01" step="0.01" class="input" required/></div><div><label class="label">Data/hora</label><input v-model="form.paid_at" type="datetime-local" class="input" required/></div></div><div><label class="label">Identificador externo</label><input v-model="form.external_id" class="input" placeholder="MANUAL-2026-0001" required/></div><div><label class="label">Forma</label><select v-model="form.payment_method" class="select"><option>TRANSFER</option><option>PIX</option><option>BOLETO</option><option>CASH</option></select></div><div class="flex justify-end gap-2"><button type="button" class="btn-secondary" @click="modal=false">Cancelar</button><button class="btn-primary"><HandCoins :size="18"/> Confirmar pagamento</button></div></form></ModalDialog></template>
