<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Building2, Pencil, Plus } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import type { ApiResponse, Company } from '../types'
import PageHeader from '../components/PageHeader.vue'
import ModalDialog from '../components/ModalDialog.vue'
import InlineAlert from '../components/InlineAlert.vue'

const items=ref<Company[]>([]);const modal=ref(false);const editing=ref<Company|null>(null);const error=ref('');const success=ref('')
const form=reactive({legal_name:'',trade_name:'',tax_id:'',state_registration:'',municipal_registration:'',tax_regime:'',email:'',phone:'',address:{street:'',number:'',district:'',city:'',state:'BA',zip_code:''},branding:{name:'',primary_color:'#0f766e',secondary_color:'#0f172a'},is_active:true})
const text=(value:unknown)=>typeof value==='string'?value:''
async function load(){error.value='';try{items.value=(await api.get<ApiResponse<Company[]>>('/v1/companies')).data.data}catch(e){error.value=apiError(e)}}
function open(item?:Company){editing.value=item||null;const address=item?.address||{};const branding=item?.branding||{};Object.assign(form,{legal_name:item?.legal_name||'',trade_name:item?.trade_name||'',tax_id:item?.tax_id||'',state_registration:'',municipal_registration:'',tax_regime:'',email:item?.email||'',phone:item?.phone||'',address:{street:text(address.street),number:text(address.number),district:text(address.district),city:text(address.city),state:text(address.state)||'BA',zip_code:text(address.zip_code)},branding:{name:text(branding.name)||item?.trade_name||item?.legal_name||'',primary_color:text(branding.primary_color)||'#0f766e',secondary_color:text(branding.secondary_color)||'#0f172a'},is_active:item?.is_active??true});modal.value=true}
async function save(){error.value='';try{const editable={legal_name:form.legal_name,trade_name:form.trade_name||null,email:form.email||null,phone:form.phone||null,address:{...form.address},branding:{...form.branding},is_active:form.is_active};if(editing.value){await api.patch(`/v1/companies/${editing.value.id}`,editable)}else{await api.post('/v1/companies',{...editable,tax_id:form.tax_id,state_registration:form.state_registration||null,municipal_registration:form.municipal_registration||null,tax_regime:form.tax_regime||null})}modal.value=false;success.value=editing.value?'Empresa atualizada.':'Empresa cadastrada.';await load()}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>
<template><PageHeader title="Empresas" subtitle="CNPJs emissores de cobranças e documentos financeiros."><button class="btn-primary" @click="open()"><Plus :size="18"/> Nova empresa</button></PageHeader><InlineAlert :message="error" @dismiss="error=''"/><InlineAlert :message="success" type="success" @dismiss="success=''"/><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><article v-for="item in items" :key="item.id" class="card"><div class="flex items-start gap-3"><div class="rounded-xl bg-teal-50 p-3 text-teal-700"><Building2 :size="22"/></div><div class="min-w-0 flex-1"><h2 class="truncate font-semibold">{{item.trade_name||item.legal_name}}</h2><p class="mt-1 truncate text-sm text-slate-500">{{item.legal_name}}</p><p class="mt-3 text-xs text-slate-400">{{item.tax_id}}</p><p class="mt-1 text-xs text-slate-400">{{item.email||'Sem e-mail'}}</p></div><button class="btn-secondary px-3 py-2" title="Editar empresa" @click="open(item)"><Pencil :size="16"/></button></div></article><div v-if="!items.length" class="card md:col-span-2 xl:col-span-3 text-center text-slate-400">Nenhuma empresa cadastrada.</div></div>
<ModalDialog :open="modal" :title="editing?'Editar empresa emissora':'Cadastrar empresa emissora'" size="xl" @close="modal=false"><form class="grid gap-4 md:grid-cols-2" @submit.prevent="save"><div><label class="label">Razão social</label><input v-model="form.legal_name" class="input" required/></div><div><label class="label">Nome fantasia</label><input v-model="form.trade_name" class="input"/></div><div><label class="label">CNPJ/CPF</label><input v-model="form.tax_id" class="input" :disabled="!!editing" required/><p v-if="editing" class="mt-1 text-xs text-slate-400">O documento identifica a empresa e não é alterado nesta tela.</p></div><div v-if="!editing"><label class="label">Regime tributário</label><select v-model="form.tax_regime" class="select"><option value="">Não informado</option><option value="SIMPLES_NACIONAL">Simples Nacional</option><option value="LUCRO_PRESUMIDO">Lucro Presumido</option><option value="LUCRO_REAL">Lucro Real</option></select></div><div><label class="label">E-mail</label><input v-model="form.email" type="email" class="input"/></div><div><label class="label">Telefone</label><input v-model="form.phone" class="input"/></div><div class="md:col-span-2 border-t pt-4 font-semibold">Endereço</div><div><label class="label">Logradouro</label><input v-model="form.address.street" class="input"/></div><div><label class="label">Número</label><input v-model="form.address.number" class="input"/></div><div><label class="label">Bairro</label><input v-model="form.address.district" class="input"/></div><div><label class="label">Cidade</label><input v-model="form.address.city" class="input"/></div><div class="grid grid-cols-[1fr_2fr] gap-2"><div><label class="label">UF</label><input v-model="form.address.state" maxlength="2" class="input uppercase"/></div><div><label class="label">CEP</label><input v-model="form.address.zip_code" class="input"/></div></div><div class="md:col-span-2 border-t pt-4 font-semibold">Identidade visual</div><div><label class="label">Nome exibido</label><input v-model="form.branding.name" class="input"/></div><div class="grid grid-cols-2 gap-2"><div><label class="label">Cor principal</label><input v-model="form.branding.primary_color" type="color" class="input h-11 p-1"/></div><div><label class="label">Cor secundária</label><input v-model="form.branding.secondary_color" type="color" class="input h-11 p-1"/></div></div><label v-if="editing" class="md:col-span-2 flex items-center gap-2 text-sm"><input v-model="form.is_active" type="checkbox"/> Empresa ativa</label><div class="md:col-span-2 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="modal=false">Cancelar</button><button class="btn-primary">{{editing?'Salvar alterações':'Salvar empresa'}}</button></div></form></ModalDialog></template>
