<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Building2, Plus } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import type { ApiResponse, Company } from '../types'
import PageHeader from '../components/PageHeader.vue'
import ModalDialog from '../components/ModalDialog.vue'

const items=ref<Company[]>([]);const modal=ref(false);const error=ref('')
const form=reactive({legal_name:'',trade_name:'',tax_id:'',state_registration:'',municipal_registration:'',tax_regime:'',email:'',phone:'',address:{street:'',number:'',district:'',city:'',state:'BA',zip_code:''},branding:{name:'',primary_color:'#0f766e',secondary_color:'#0f172a'}})
async function load(){try{items.value=(await api.get<ApiResponse<Company[]>>('/v1/companies')).data.data}catch(e){error.value=apiError(e)}}
async function create(){try{await api.post('/v1/companies',form);modal.value=false;await load()}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>
<template><PageHeader title="Empresas" subtitle="CNPJs emissores de cobrança dentro deste tenant."><button class="btn-primary" @click="modal=true"><Plus :size="18"/> Nova empresa</button></PageHeader><p v-if="error" class="mb-5 rounded-xl bg-rose-50 p-3 text-rose-700">{{error}}</p><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><article v-for="item in items" :key="item.id" class="card"><div class="flex items-start gap-3"><div class="rounded-xl bg-teal-50 p-3 text-teal-700"><Building2 :size="22"/></div><div class="min-w-0"><h2 class="truncate font-semibold">{{item.trade_name||item.legal_name}}</h2><p class="mt-1 truncate text-sm text-slate-500">{{item.legal_name}}</p><p class="mt-3 text-xs text-slate-400">{{item.tax_id}}</p><p class="mt-1 text-xs text-slate-400">{{item.email||'Sem e-mail'}}</p></div></div></article><div v-if="!items.length" class="card md:col-span-2 xl:col-span-3 text-center text-slate-400">Nenhuma empresa cadastrada.</div></div>
<ModalDialog :open="modal" title="Cadastrar empresa emissora" size="xl" @close="modal=false"><form class="grid gap-4 md:grid-cols-2" @submit.prevent="create"><div><label class="label">Razão social</label><input v-model="form.legal_name" class="input" required/></div><div><label class="label">Nome fantasia</label><input v-model="form.trade_name" class="input"/></div><div><label class="label">CNPJ/CPF</label><input v-model="form.tax_id" class="input" required/></div><div><label class="label">Regime tributário</label><select v-model="form.tax_regime" class="select"><option value="">Não informado</option><option>SIMPLES_NACIONAL</option><option>LUCRO_PRESUMIDO</option><option>LUCRO_REAL</option></select></div><div><label class="label">E-mail</label><input v-model="form.email" type="email" class="input"/></div><div><label class="label">Telefone</label><input v-model="form.phone" class="input"/></div><div class="md:col-span-2 border-t pt-4 font-semibold">Endereço</div><div><label class="label">Logradouro</label><input v-model="form.address.street" class="input"/></div><div><label class="label">Número</label><input v-model="form.address.number" class="input"/></div><div><label class="label">Cidade</label><input v-model="form.address.city" class="input"/></div><div class="grid grid-cols-[1fr_2fr] gap-2"><div><label class="label">UF</label><input v-model="form.address.state" maxlength="2" class="input"/></div><div><label class="label">CEP</label><input v-model="form.address.zip_code" class="input"/></div></div><div class="md:col-span-2 border-t pt-4 font-semibold">Identidade do tenant</div><div><label class="label">Nome exibido</label><input v-model="form.branding.name" class="input"/></div><div class="grid grid-cols-2 gap-2"><div><label class="label">Cor principal</label><input v-model="form.branding.primary_color" type="color" class="input h-11 p-1"/></div><div><label class="label">Cor secundária</label><input v-model="form.branding.secondary_color" type="color" class="input h-11 p-1"/></div></div><div class="md:col-span-2 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="modal=false">Cancelar</button><button class="btn-primary">Salvar empresa</button></div></form></ModalDialog></template>
