<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus, Search, UserRound } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import type { Customer, Paginated } from '../types'
import PageHeader from '../components/PageHeader.vue'
import ModalDialog from '../components/ModalDialog.vue'

const items=ref<Customer[]>([]);const modal=ref(false);const error=ref('');const q=ref('');const loading=ref(false)
const form=reactive({person_type:'PJ',name:'',trade_name:'',tax_id:'',email:'',phone:'',whatsapp:'',address:{street:'',number:'',district:'',city:'',state:'BA',zip_code:''},tags:[] as string[],notes:'',contacts:[] as unknown[]})
async function load(){loading.value=true;try{items.value=(await api.get<Paginated<Customer>>('/v1/customers',{params:{q:q.value||undefined,per_page:100}})).data.data}catch(e){error.value=apiError(e)}finally{loading.value=false}}
async function create(){try{await api.post('/v1/customers',form);modal.value=false;Object.assign(form,{person_type:'PJ',name:'',trade_name:'',tax_id:'',email:'',phone:'',whatsapp:'',address:{street:'',number:'',district:'',city:'',state:'BA',zip_code:''},tags:[],notes:'',contacts:[]});await load()}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>
<template><PageHeader title="Clientes" subtitle="Sacados, responsáveis financeiros e contatos de cobrança."><button class="btn-primary" @click="modal=true"><Plus :size="18"/> Novo cliente</button></PageHeader><div class="mb-5 max-w-md"><div class="relative"><Search class="absolute left-3.5 top-3 text-slate-400" :size="18"/><input v-model="q" class="input pl-10" placeholder="Nome, fantasia ou CPF/CNPJ" @keyup.enter="load"/></div></div><p v-if="error" class="mb-5 rounded-xl bg-rose-50 p-3 text-rose-700">{{error}}</p><div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>Documento</th><th>Contato</th><th>Tags</th><th>Status</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><div class="flex items-center gap-3"><div class="rounded-xl bg-slate-100 p-2 text-slate-500"><UserRound :size="18"/></div><div><p class="font-semibold">{{item.name}}</p><p class="text-xs text-slate-400">{{item.trade_name}}</p></div></div></td><td>{{item.tax_id||'—'}}</td><td><p>{{item.email||'—'}}</p><p class="text-xs text-slate-400">{{item.whatsapp||item.phone}}</p></td><td><span v-for="tag in item.tags" :key="tag" class="badge mr-1 bg-slate-100 text-slate-600">{{tag}}</span></td><td><span class="badge" :class="item.is_active?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600'">{{item.is_active?'Ativo':'Inativo'}}</span></td></tr><tr v-if="!items.length"><td colspan="5" class="py-12 text-center text-slate-400">Nenhum cliente encontrado.</td></tr></tbody></table></div>
<ModalDialog :open="modal" title="Cadastrar cliente" size="xl" @close="modal=false"><form class="grid gap-4 md:grid-cols-2" @submit.prevent="create"><div><label class="label">Tipo</label><select v-model="form.person_type" class="select"><option value="PJ">Pessoa jurídica</option><option value="PF">Pessoa física</option></select></div><div><label class="label">CPF/CNPJ</label><input v-model="form.tax_id" class="input"/></div><div><label class="label">Nome / razão social</label><input v-model="form.name" class="input" required/></div><div><label class="label">Nome fantasia</label><input v-model="form.trade_name" class="input"/></div><div><label class="label">E-mail financeiro</label><input v-model="form.email" type="email" class="input"/></div><div><label class="label">WhatsApp</label><input v-model="form.whatsapp" class="input" placeholder="5575999999999"/></div><div><label class="label">Telefone</label><input v-model="form.phone" class="input"/></div><div><label class="label">Tags</label><input class="input" placeholder="Use o cadastro após salvar" disabled/></div><div class="md:col-span-2 border-t pt-4 font-semibold">Endereço</div><div><label class="label">Logradouro</label><input v-model="form.address.street" class="input"/></div><div><label class="label">Número</label><input v-model="form.address.number" class="input"/></div><div><label class="label">Cidade</label><input v-model="form.address.city" class="input"/></div><div class="grid grid-cols-[1fr_2fr] gap-2"><div><label class="label">UF</label><input v-model="form.address.state" maxlength="2" class="input"/></div><div><label class="label">CEP</label><input v-model="form.address.zip_code" class="input"/></div></div><div class="md:col-span-2"><label class="label">Observações</label><textarea v-model="form.notes" class="input min-h-24"></textarea></div><div class="md:col-span-2 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="modal=false">Cancelar</button><button class="btn-primary">Salvar cliente</button></div></form></ModalDialog></template>
