<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Download, FileSpreadsheet, FileText, Plus, RefreshCw } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import type { ApiResponse } from '../types'
import PageHeader from '../components/PageHeader.vue'
import SectionTabs from '../components/SectionTabs.vue'
import DrawerPanel from '../components/DrawerPanel.vue'
import InlineAlert from '../components/InlineAlert.vue'
import StatusBadge from '../components/StatusBadge.vue'
import EmptyState from '../components/EmptyState.vue'
import { dateTimeBR, formatBytes } from '../utils/format'

interface DocumentItem { id:string;company_id?:string;entity_type:string;entity_id?:string;document_type:string;filename:string;mime_type:string;size_bytes:number;sha256:string;version:number;created_at:string;download_url:string }
interface ExportJob { id:string;export_type:string;status:string;format:string;filters:Record<string,unknown>;size_bytes?:number;sha256?:string;created_at:string;finished_at?:string;last_error?:string;download_url?:string }
const tab=ref('documents');const documents=ref<DocumentItem[]>([]);const exports=ref<ExportJob[]>([]);const drawer=ref(false);const error=ref('');const success=ref('');const type=ref('');const form=reactive({export_type:'RECEIVABLES',format:'XLSX',filters:'{}'})
async function load(){try{const [d,e]=await Promise.all([api.get<ApiResponse<DocumentItem[]>>('/v1/documents',{params:{entity_type:type.value||undefined}}),api.get<ApiResponse<ExportJob[]>>('/v1/exports')]);documents.value=d.data.data;exports.value=e.data.data}catch(exception){error.value=apiError(exception)}}
async function createExport(){try{const response=await api.post<ApiResponse<{download_url?:string}>>('/v1/exports',{export_type:form.export_type,format:form.format,filters:JSON.parse(form.filters||'{}')});drawer.value=false;success.value='Exportação concluída.';if(response.data.data.download_url)window.open(response.data.data.download_url,'_blank');await load()}catch(exception){error.value=apiError(exception)}}
onMounted(load)
</script>
<template><PageHeader title="Documentos e exportações" subtitle="Arquivos financeiros imutáveis, versões, SHA-256 e relatórios sob demanda."><button class="btn-secondary" @click="load"><RefreshCw :size="18"/>Atualizar</button><button class="btn-primary" @click="drawer=true"><Plus :size="18"/>Nova exportação</button></PageHeader><InlineAlert :message="error" @dismiss="error=''"/><InlineAlert :message="success" type="success" @dismiss="success=''"/><SectionTabs v-model="tab" :items="[{key:'documents',label:'Documentos',count:documents.length},{key:'exports',label:'Exportações',count:exports.length}]"/>
<div v-if="tab==='documents'"><div class="mb-4 max-w-xs"><select v-model="type" class="select" @change="load"><option value="">Todos os tipos de entidade</option><option>Charge</option><option>Payment</option><option>Receipt</option><option>FiscalDocument</option><option>CNABRemittance</option><option>CNABReturn</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>Arquivo</th><th>Tipo / entidade</th><th>Versão</th><th>Tamanho</th><th>Integridade</th><th>Data</th><th></th></tr></thead><tbody><tr v-for="item in documents" :key="item.id"><td><p class="inline-flex items-center gap-2 font-semibold"><FileText :size="17" class="text-teal-700"/>{{item.filename}}</p><p class="text-xs text-slate-400">{{item.mime_type}}</p></td><td>{{item.document_type}}<p class="text-xs text-slate-400">{{item.entity_type}} · {{item.entity_id||'—'}}</p></td><td>v{{item.version}}</td><td>{{formatBytes(item.size_bytes)}}</td><td><p class="max-w-[220px] truncate font-mono text-[10px]">{{item.sha256}}</p></td><td>{{dateTimeBR(item.created_at)}}</td><td><a :href="item.download_url" target="_blank" class="btn-secondary !px-3 !py-2"><Download :size="15"/></a></td></tr></tbody></table><EmptyState v-if="!documents.length" title="Nenhum documento armazenado"/></div></div>
<div v-else class="table-wrap"><table class="table"><thead><tr><th>Exportação</th><th>Formato</th><th>Filtros</th><th>Tamanho / SHA</th><th>Status</th><th>Data</th><th></th></tr></thead><tbody><tr v-for="item in exports" :key="item.id"><td><p class="inline-flex items-center gap-2 font-semibold"><FileSpreadsheet :size="17" class="text-teal-700"/>{{item.export_type}}</p></td><td>{{item.format}}</td><td><pre class="max-w-sm whitespace-pre-wrap text-[10px]">{{JSON.stringify(item.filters,null,1)}}</pre></td><td>{{formatBytes(item.size_bytes||0)}}<p class="max-w-[220px] truncate font-mono text-[10px] text-slate-400">{{item.sha256||'—'}}</p></td><td><StatusBadge :status="item.status"/><p v-if="item.last_error" class="mt-1 text-xs text-rose-600">{{item.last_error}}</p></td><td>{{dateTimeBR(item.created_at)}}</td><td><a v-if="item.download_url" :href="item.download_url" target="_blank" class="btn-secondary !px-3 !py-2"><Download :size="15"/></a></td></tr></tbody></table><EmptyState v-if="!exports.length" title="Nenhuma exportação solicitada"/></div>
<DrawerPanel :open="drawer" title="Gerar exportação" width="lg" @close="drawer=false"><form class="space-y-4" @submit.prevent="createExport"><div class="grid gap-4 md:grid-cols-2"><div><label class="label">Tipo</label><select v-model="form.export_type" class="select"><option>RECEIVABLES</option><option>PAYMENTS</option><option>CUSTOMERS</option><option>CONTRACTS</option><option>CHARGES</option><option>AUDIT</option></select></div><div><label class="label">Formato</label><select v-model="form.format" class="select"><option>XLSX</option><option>CSV</option><option>JSON</option></select></div></div><div><label class="label">Filtros JSON</label><textarea v-model="form.filters" class="input min-h-40 font-mono text-xs"/></div><div class="flex justify-end gap-2"><button type="button" class="btn-secondary" @click="drawer=false">Cancelar</button><button class="btn-primary">Gerar arquivo</button></div></form></DrawerPanel></template>
