<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Download, FileSpreadsheet, Plus, RefreshCw } from 'lucide-vue-next'
import { api, apiError } from '../api/client';import type { ApiResponse } from '../types'
import PageHeader from '../components/PageHeader.vue';import DrawerPanel from '../components/DrawerPanel.vue';import InlineAlert from '../components/InlineAlert.vue';import JsonEditor from '../components/JsonEditor.vue';import StatusBadge from '../components/StatusBadge.vue';import EmptyState from '../components/EmptyState.vue'
interface ExportJob{id:string;export_type:string;status:string;format:string;filters:Record<string,unknown>;size_bytes?:number;sha256?:string;created_at:string;finished_at?:string;last_error?:string;download_url?:string}
const items=ref<ExportJob[]>([]),drawer=ref(false),error=ref(''),success=ref('');const form=reactive({export_type:'RECEIVABLES',format:'XLSX',filters:'{}'})
const size=(v?:number)=>v?`${(v/1024).toFixed(1)} KB`:'—'
async function load(){try{items.value=(await api.get<ApiResponse<ExportJob[]>>('/v1/exports')).data.data}catch(e){error.value=apiError(e)}}
async function create(){try{const r=(await api.post<ApiResponse<ExportJob>>('/v1/exports',{export_type:form.export_type,format:form.format,filters:JSON.parse(form.filters)})).data.data;drawer.value=false;success.value='Exportação concluída.';if(r.download_url)window.open(r.download_url,'_blank');await load()}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>
<template><PageHeader title="Exportações" subtitle="Relatórios de dados em XLSX e CSV armazenados no namespace do tenant."><button class="btn-secondary" @click="load"><RefreshCw :size="18"/>Atualizar</button><button class="btn-primary" @click="drawer=true"><Plus :size="18"/>Nova exportação</button></PageHeader><InlineAlert :message="error" @dismiss="error=''"/><InlineAlert :message="success" type="success" @dismiss="success=''"/><div class="table-wrap"><table class="table"><thead><tr><th>Exportação</th><th>Formato</th><th>Filtros</th><th>Tamanho</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="item in items" :key="item.id" class="border-t border-slate-100"><td><div class="flex items-center gap-2"><FileSpreadsheet :size="17" class="text-emerald-600"/><div><p class="font-semibold">{{item.export_type}}</p><p class="text-xs text-slate-400">{{new Date(item.created_at).toLocaleString('pt-BR')}}</p></div></div></td><td>{{item.format}}</td><td><pre class="max-w-md truncate text-xs">{{JSON.stringify(item.filters)}}</pre></td><td>{{size(item.size_bytes)}}<p v-if="item.sha256" class="font-mono text-xs text-slate-400">{{item.sha256.slice(0,12)}}…</p></td><td><StatusBadge :status="item.status"/><p v-if="item.last_error" class="text-xs text-rose-600">{{item.last_error}}</p></td><td class="text-right"><a v-if="item.download_url" class="btn-secondary px-3 py-2" :href="item.download_url"><Download :size="16"/>Baixar</a></td></tr></tbody></table><EmptyState v-if="!items.length" title="Nenhuma exportação"/></div><DrawerPanel :open="drawer" title="Nova exportação" width="lg" @close="drawer=false"><form class="space-y-4" @submit.prevent="create"><div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Tipo</label><select v-model="form.export_type" class="select"><option>RECEIVABLES</option><option>PAYMENTS</option><option>CUSTOMERS</option><option>CONTRACTS</option><option>CHARGES</option><option>CNAB_EVENTS</option><option>AUDIT</option></select></div><div><label class="label">Formato</label><select v-model="form.format" class="select"><option>XLSX</option><option>CSV</option></select></div></div><JsonEditor v-model="form.filters" label="Filtros JSON"/><div class="flex justify-end gap-2"><button type="button" class="btn-secondary" @click="drawer=false">Cancelar</button><button class="btn-primary">Gerar</button></div></form></DrawerPanel></template>
