<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { CheckCircle2, FileArchive, Upload, WandSparkles } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import type { ApiResponse, Company, ServiceItem } from '../types'
import PageHeader from '../components/PageHeader.vue'

interface PreviewRecord { name:string;amount:string;due_date?:string|null;billing_method:string;tax_id?:string|null;email?:string|null;whatsapp?:string|null;source_files:string[] }
interface Preview { competence:string;records:PreviewRecord[];warnings:string[];source_counts:Record<string,number> }
const companies=ref<Company[]>([]);const services=ref<ServiceItem[]>([]);const file=ref<File|null>(null);const preview=ref<Preview|null>(null);const error=ref('');const message=ref('');const loading=ref(false)
const form=reactive({company_id:'',service_id:'',create_contracts:true,create_receivables:true})
const money=(value:string)=>Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
async function load(){try{const [c,s]=await Promise.all([api.get<ApiResponse<Company[]>>('/v1/companies'),api.get<ApiResponse<ServiceItem[]>>('/v1/services')]);companies.value=c.data.data;services.value=s.data.data;form.company_id ||= companies.value[0]?.id||'';form.service_id ||= services.value[0]?.id||''}catch(e){error.value=apiError(e)}}
function selectFile(event:Event){file.value=(event.target as HTMLInputElement).files?.[0]||null;preview.value=null;message.value=''}
async function previewFile(){if(!file.value)return;loading.value=true;error.value='';try{const data=new FormData();data.append('file',file.value);const response=await api.post<ApiResponse<Preview>>('/v1/imports/financial-vitor/preview',data,{headers:{'Content-Type':'multipart/form-data'}});preview.value=response.data.data}catch(e){error.value=apiError(e)}finally{loading.value=false}}
async function importFile(){if(!file.value)return;loading.value=true;error.value='';try{const data=new FormData();data.append('file',file.value);data.append('company_id',form.company_id);data.append('service_id',form.service_id);data.append('create_contracts',String(form.create_contracts));data.append('create_receivables',String(form.create_receivables));const response=await api.post<ApiResponse<Record<string,number>>>('/v1/imports/financial-vitor',data,{headers:{'Content-Type':'multipart/form-data'}});message.value=`Importação concluída: ${Object.entries(response.data.data).map(([k,v])=>`${k}=${v}`).join(', ')}.`}catch(e){error.value=apiError(e)}finally{loading.value=false}}
onMounted(load)
</script>
<template>
<PageHeader title="Importação de dados" subtitle="Migração segura e auditável do pacote financeiro legado para clientes, contratos e recebíveis."/>
<p v-if="error" class="mb-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{{error}}</p><p v-if="message" class="mb-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{{message}}</p>
<div class="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><section class="card"><div class="flex items-center gap-3"><div class="rounded-2xl bg-violet-50 p-3 text-violet-700"><FileArchive :size="24"/></div><div><h2 class="font-bold">FINANCEIRO Vitor.zip</h2><p class="text-sm text-slate-500">Honorários, boletos, recibos, notas e contatos.</p></div></div><label class="mt-6 block cursor-pointer rounded-2xl border-2 border-dashed border-slate-200 p-8 text-center hover:border-teal-400"><Upload :size="30" class="mx-auto text-slate-400"/><p class="mt-3 font-semibold">{{file?.name||'Selecione o arquivo ZIP'}}</p><p class="mt-1 text-xs text-slate-400">Limite 100 MB · validação contra caminhos inseguros</p><input type="file" accept=".zip" class="hidden" @change="selectFile"/></label><div class="mt-5 grid gap-4"><div><label class="label">Empresa emissora</label><select v-model="form.company_id" class="select"><option v-for="item in companies" :key="item.id" :value="item.id">{{item.trade_name||item.legal_name}}</option></select></div><div><label class="label">Serviço padrão</label><select v-model="form.service_id" class="select"><option v-for="item in services" :key="item.id" :value="item.id">{{item.code}} · {{item.name}}</option></select></div><label class="flex items-center gap-2 text-sm"><input v-model="form.create_contracts" type="checkbox"/> Criar contratos recorrentes</label><label class="flex items-center gap-2 text-sm"><input v-model="form.create_receivables" type="checkbox"/> Criar recebíveis da competência</label></div><div class="mt-6 flex gap-2"><button class="btn-secondary flex-1" :disabled="!file||loading" @click="previewFile"><WandSparkles :size="18"/> Analisar</button><button class="btn-primary flex-1" :disabled="!file||!preview||loading" @click="importFile"><CheckCircle2 :size="18"/> Importar</button></div></section>
<section><div v-if="preview" class="space-y-5"><div class="grid gap-3 sm:grid-cols-3"><div class="card"><p class="text-xs uppercase text-slate-400">Competência</p><p class="mt-2 text-xl font-bold">{{preview.competence}}</p></div><div class="card"><p class="text-xs uppercase text-slate-400">Registros</p><p class="mt-2 text-xl font-bold">{{preview.records.length}}</p></div><div class="card"><p class="text-xs uppercase text-slate-400">Alertas</p><p class="mt-2 text-xl font-bold">{{preview.warnings.length}}</p></div></div><div v-if="preview.warnings.length" class="rounded-2xl border border-amber-200 bg-amber-50 p-4"><h3 class="font-semibold text-amber-900">Pontos para conferência</h3><div class="mt-2 max-h-32 overflow-auto text-xs text-amber-800"><p v-for="warning in preview.warnings" :key="warning">• {{warning}}</p></div></div><div class="table-wrap max-h-[600px] overflow-auto"><table class="table"><thead class="sticky top-0"><tr><th>Cliente</th><th>Documento/contato</th><th>Forma</th><th>Vencimento</th><th>Valor</th></tr></thead><tbody><tr v-for="item in preview.records" :key="item.name"><td><p class="font-semibold">{{item.name}}</p><p class="text-xs text-slate-400">{{item.source_files.join(', ')}}</p></td><td><p class="text-xs">{{item.tax_id||'Documento não localizado'}}</p><p class="text-xs text-slate-400">{{item.email||item.whatsapp||'Contato não localizado'}}</p></td><td>{{item.billing_method}}</td><td>{{item.due_date?new Date(item.due_date+'T12:00:00').toLocaleDateString('pt-BR'):'—'}}</td><td class="font-semibold">{{money(item.amount)}}</td></tr></tbody></table></div></div><div v-else class="card grid min-h-80 place-items-center text-center text-slate-400"><div><FileArchive :size="42" class="mx-auto"/><p class="mt-3 font-semibold">Selecione e analise um pacote para visualizar a prévia.</p></div></div></section></div>
</template>
