<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Activity, ArchiveRestore, Cloud, Database, Download, HardDrive, Play, RefreshCw } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import type { ApiResponse } from '../types'
import PageHeader from '../components/PageHeader.vue'
import StatusBadge from '../components/StatusBadge.vue'

interface Health { status:string;version:string;checks:Record<string,string> }
interface Backup { id:string;scope:string;status:string;checksum?:string|null;size_bytes?:number|null;started_at?:string|null;finished_at?:string|null;last_error?:string|null;destinations:Record<string,unknown>;download_url?:string|null }
interface Policy { enabled:boolean;cron:string;retention:{daily:number;weekly:number;monthly:number};encryption_enabled:boolean;destinations:{local:boolean;s3:boolean;google_drive:boolean;dropbox:boolean} }
const health=ref<Health|null>(null);const backups=ref<Backup[]>([]);const policy=ref<Policy|null>(null);const error=ref('');const message=ref('');const loading=ref(false)
const latest=computed(()=>backups.value[0]||null)
const bytes=(value?:number|null)=>{if(!value)return'—';const units=['B','KB','MB','GB','TB'];let size=value,index=0;while(size>=1024&&index<units.length-1){size/=1024;index++}return`${size.toFixed(index?2:0)} ${units[index]}`}
async function load(){loading.value=true;error.value='';try{const [h,b,p]=await Promise.all([fetch('/health/ready').then(r=>r.json()),api.get<ApiResponse<Backup[]>>('/control/v1/backups'),api.get<ApiResponse<Policy>>('/control/v1/backup-policy')]);health.value=h;backups.value=b.data.data;policy.value=p.data.data}catch(e){error.value=apiError(e)}finally{loading.value=false}}
async function runBackup(){error.value='';try{const r=await api.post<ApiResponse<{task_id:string}>>('/control/v1/backups');message.value=`Backup integral enfileirado. Task ${r.data.data.task_id}.`;setTimeout(load,2000)}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>
<template>
<PageHeader title="Operação e backups" subtitle="Prontidão dos componentes, política de retenção e cópias integrais da plataforma."><button class="btn-secondary" :disabled="loading" @click="load"><RefreshCw :size="18" :class="loading?'animate-spin':''"/> Atualizar</button><button class="btn-primary" @click="runBackup"><Play :size="18"/> Executar backup</button></PageHeader>
<p v-if="error" class="mb-5 rounded-xl bg-rose-50 p-3 text-rose-700">{{error}}</p><p v-if="message" class="mb-5 rounded-xl bg-blue-50 p-3 text-blue-700">{{message}}</p>
<div v-if="health" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="card"><p class="text-sm text-slate-500">Aplicação</p><div class="mt-3"><StatusBadge :status="health.status==='ok'?'ACTIVE':'ERROR'"/></div><p class="mt-2 text-xs text-slate-400">Versão {{health.version}}</p></div><div v-for="(value,key) in health.checks" :key="key" class="card"><p class="text-sm capitalize text-slate-500">{{key}}</p><div class="mt-3"><StatusBadge :status="value==='ok'?'ACTIVE':'ERROR'"/></div><p class="mt-2 text-xs text-slate-400">{{value}}</p></div><div class="card"><p class="text-sm text-slate-500">Último backup</p><div class="mt-3"><StatusBadge :status="latest?.status||'PENDING'"/></div><p class="mt-2 text-xs text-slate-400">{{latest?.finished_at?new Date(latest.finished_at).toLocaleString('pt-BR'):'Nenhum concluído'}}</p></div></div>
<div v-if="policy" class="mt-6 grid gap-5 lg:grid-cols-2"><section class="card"><div class="flex items-center gap-3"><div class="rounded-xl bg-teal-50 p-3 text-teal-700"><ArchiveRestore :size="22"/></div><div><h2 class="font-semibold">Política de backup</h2><p class="text-sm text-slate-500">Agendamento: {{policy.cron}}</p></div></div><div class="mt-5 grid grid-cols-3 gap-3 text-center"><div class="rounded-xl bg-slate-50 p-3"><p class="text-xl font-bold">{{policy.retention.daily}}</p><p class="text-xs text-slate-500">Diários</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-xl font-bold">{{policy.retention.weekly}}</p><p class="text-xs text-slate-500">Semanais</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-xl font-bold">{{policy.retention.monthly}}</p><p class="text-xs text-slate-500">Mensais</p></div></div></section><section class="card"><div class="flex items-center gap-3"><div class="rounded-xl bg-blue-50 p-3 text-blue-700"><Cloud :size="22"/></div><div><h2 class="font-semibold">Destinos</h2><p class="text-sm text-slate-500">Criptografia: {{policy.encryption_enabled?'Ativa':'Opcional/desativada'}}</p></div></div><div class="mt-5 flex flex-wrap gap-2"><span v-for="(enabled,name) in policy.destinations" :key="name" class="badge" :class="enabled?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-400'">{{name}} · {{enabled?'ativo':'inativo'}}</span></div></section></div>
<section class="mt-7"><h2 class="mb-3 text-lg font-semibold">Histórico de backups</h2><div class="table-wrap"><table class="table"><thead><tr><th>Início</th><th>Escopo</th><th>Tamanho</th><th>SHA-256</th><th>Destinos</th><th>Status</th><th>Arquivo</th></tr></thead><tbody><tr v-for="item in backups" :key="item.id"><td>{{item.started_at?new Date(item.started_at).toLocaleString('pt-BR'):'—'}}</td><td>{{item.scope}}</td><td>{{bytes(item.size_bytes)}}</td><td class="max-w-xs truncate font-mono text-[10px]">{{item.checksum||'—'}}</td><td><div class="flex flex-wrap gap-1"><span v-for="(_,name) in item.destinations" :key="name" class="badge bg-slate-100 text-slate-600">{{name}}</span></div></td><td><StatusBadge :status="item.status"/><p v-if="item.last_error" class="mt-1 max-w-sm text-xs text-rose-600">{{item.last_error}}</p></td><td><a v-if="item.download_url" class="inline-flex items-center gap-1 text-xs font-semibold text-teal-700" :href="item.download_url" target="_blank"><Download :size="15"/> Baixar</a></td></tr><tr v-if="!backups.length"><td colspan="7" class="py-10 text-center text-slate-400">Nenhum backup registrado.</td></tr></tbody></table></div></section>
</template>
