<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Banknote, Plus, RefreshCw, Repeat2 } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import type { ApiResponse, Company, Customer, Paginated, Receivable } from '../types'
import PageHeader from '../components/PageHeader.vue'
import ModalDialog from '../components/ModalDialog.vue'
import StatusBadge from '../components/StatusBadge.vue'

const items=ref<Receivable[]>([]);const companies=ref<Company[]>([]);const customers=ref<Customer[]>([]);const modal=ref(false);const error=ref('');const status=ref('')
const today=new Date().toISOString().slice(0,10);const competence=today.slice(0,7)
const form=reactive({company_id:'',customer_id:'',contract_id:null as string|null,competence,description:'Cobrança avulsa',issue_date:today,due_date:today,original_amount:'0.00',discount_amount:'0.00'})
const companyName=(id:string)=>companies.value.find(x=>x.id===id)?.trade_name||companies.value.find(x=>x.id===id)?.legal_name||id
const customerName=(id:string)=>customers.value.find(x=>x.id===id)?.name||id
const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
async function load(){try{const [a,b,c]=await Promise.all([api.get<Paginated<Receivable>>('/v1/receivables',{params:{per_page:100,status:status.value||undefined}}),api.get<ApiResponse<Company[]>>('/v1/companies'),api.get<Paginated<Customer>>('/v1/customers',{params:{per_page:100}})]);items.value=a.data.data;companies.value=b.data.data;customers.value=c.data.data;if(!form.company_id&&companies.value[0])form.company_id=companies.value[0].id}catch(e){error.value=apiError(e)}}
async function create(){try{await api.post('/v1/receivables',form);modal.value=false;await load()}catch(e){error.value=apiError(e)}}
async function generate(){try{await api.post('/v1/recurrences/generate');await load()}catch(e){error.value=apiError(e)}}
async function charge(item:Receivable){try{await api.post('/v1/charges',{receivable_id:item.id,charge_type:'BOLETO_PIX',provider:'SANDBOX'});await load()}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>
<template><PageHeader title="Contas a receber" subtitle="Títulos manuais e gerados por recorrência."><button class="btn-secondary" @click="generate"><Repeat2 :size="18"/> Gerar recorrências</button><button class="btn-primary" @click="modal=true"><Plus :size="18"/> Novo recebível</button></PageHeader><div class="mb-5 flex max-w-sm gap-2"><select v-model="status" class="select" @change="load"><option value="">Todos os status</option><option>OPEN</option><option>REGISTERED</option><option>PARTIALLY_PAID</option><option>PAID</option><option>OVERDUE</option></select><button class="btn-secondary" @click="load"><RefreshCw :size="18"/></button></div><p v-if="error" class="mb-5 rounded-xl bg-rose-50 p-3 text-rose-700">{{error}}</p><div class="table-wrap"><table class="table"><thead><tr><th>Título</th><th>Empresa / Cliente</th><th>Vencimento</th><th>Valor</th><th>Saldo</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><p class="font-semibold">{{item.document_number}}</p><p class="text-xs text-slate-400">{{item.description}} · {{item.competence}}</p></td><td><p>{{companyName(item.company_id)}}</p><p class="text-xs text-slate-400">{{customerName(item.customer_id)}}</p></td><td>{{new Date(item.due_date+'T12:00:00').toLocaleDateString('pt-BR')}}</td><td>{{money(item.original_amount)}}</td><td class="font-semibold">{{money(item.balance)}}</td><td><StatusBadge :status="item.status"/></td><td><button v-if="['OPEN','OVERDUE','PARTIALLY_PAID'].includes(item.status)" class="btn-secondary py-1.5" @click="charge(item)"><Banknote :size="15"/> Cobrar</button></td></tr><tr v-if="!items.length"><td colspan="7" class="py-12 text-center text-slate-400">Nenhum recebível encontrado.</td></tr></tbody></table></div>
<ModalDialog :open="modal" title="Criar conta a receber" size="lg" @close="modal=false"><form class="grid gap-4 md:grid-cols-2" @submit.prevent="create"><div><label class="label">Empresa emissora</label><select v-model="form.company_id" class="select" required><option v-for="c in companies" :key="c.id" :value="c.id">{{c.trade_name||c.legal_name}}</option></select></div><div><label class="label">Cliente</label><select v-model="form.customer_id" class="select" required><option value="" disabled>Selecione</option><option v-for="c in customers" :key="c.id" :value="c.id">{{c.name}}</option></select></div><div><label class="label">Competência</label><input v-model="form.competence" type="month" class="input" required/></div><div><label class="label">Descrição</label><input v-model="form.description" class="input" required/></div><div><label class="label">Emissão</label><input v-model="form.issue_date" type="date" class="input" required/></div><div><label class="label">Vencimento</label><input v-model="form.due_date" type="date" class="input" required/></div><div><label class="label">Valor original</label><input v-model="form.original_amount" type="number" min="0.01" step="0.01" class="input" required/></div><div><label class="label">Desconto</label><input v-model="form.discount_amount" type="number" min="0" step="0.01" class="input"/></div><div class="md:col-span-2 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="modal=false">Cancelar</button><button class="btn-primary">Criar recebível</button></div></form></ModalDialog></template>
