<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { AlertTriangle, Banknote, CircleDollarSign, FileSpreadsheet, HandCoins, RefreshCw } from 'lucide-vue-next'
import { api, apiError } from '../api/client';import type { ApiResponse, Paginated, Receivable, Payment } from '../types'
import PageHeader from '../components/PageHeader.vue';import InlineAlert from '../components/InlineAlert.vue';import StatCard from '../components/StatCard.vue';import StatusBadge from '../components/StatusBadge.vue'
interface Dashboard{open_amount:string;overdue_amount:string;received_month:string;receivables_count:number;overdue_count:number;active_contracts:number;customers:number}
const data=ref<Dashboard>({open_amount:'0',overdue_amount:'0',received_month:'0',receivables_count:0,overdue_count:0,active_contracts:0,customers:0}),receivables=ref<Receivable[]>([]),payments=ref<Payment[]>([]),error=ref('')
const money=(v:string|number)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const byStatus=computed(()=>Object.entries(receivables.value.reduce<Record<string,{count:number;amount:number}>>((acc,item)=>{acc[item.status]??={count:0,amount:0};acc[item.status].count++;acc[item.status].amount+=Number(item.balance);return acc},{})).sort((a,b)=>b[1].amount-a[1].amount))
const recentPayments=computed(()=>payments.value.slice(0,10))
async function load(){try{const [d,r,p]=await Promise.all([api.get<ApiResponse<Dashboard>>('/v1/dashboard'),api.get<Paginated<Receivable>>('/v1/receivables',{params:{per_page:1000}}),api.get<ApiResponse<Payment[]>>('/v1/payments')]);data.value=d.data.data;receivables.value=r.data.data;payments.value=p.data.data}catch(e){error.value=apiError(e)}}
async function exportReceivables(){try{const r=(await api.post<ApiResponse<{download_url:string}>>('/v1/exports',{export_type:'RECEIVABLES',format:'XLSX',filters:{}})).data.data;if(r.download_url)window.open(r.download_url,'_blank')}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>
<template><PageHeader title="Relatórios financeiros" subtitle="Indicadores consolidados, carteira e exportação analítica."><button class="btn-secondary" @click="load"><RefreshCw :size="18"/>Atualizar</button><button class="btn-primary" @click="exportReceivables"><FileSpreadsheet :size="18"/>Exportar carteira</button></PageHeader><InlineAlert :message="error" @dismiss="error=''"/><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Em aberto" :value="money(data.open_amount)" :icon="CircleDollarSign" tone="blue"/><StatCard label="Vencido" :value="money(data.overdue_amount)" :hint="`${data.overdue_count} títulos`" :icon="AlertTriangle" tone="rose"/><StatCard label="Recebido no mês" :value="money(data.received_month)" :icon="HandCoins" tone="teal"/><StatCard label="Clientes" :value="data.customers" :icon="Banknote" tone="amber"/></div><div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="card"><h2 class="font-bold">Carteira por status</h2><div class="mt-4 space-y-3"><div v-for="[status,group] in byStatus" :key="status" class="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><StatusBadge :status="status"/><div class="flex-1"><div class="h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-teal-500" :style="{width:`${Math.min(100,(group.amount/Math.max(1,Number(data.open_amount)))*100)}%`}"/></div></div><div class="text-right"><p class="font-bold">{{money(group.amount)}}</p><p class="text-xs text-slate-400">{{group.count}} títulos</p></div></div></div></section><section class="card"><h2 class="font-bold">Pagamentos recentes</h2><div class="mt-4 divide-y divide-slate-100"><div v-for="item in recentPayments" :key="item.id" class="flex items-center gap-3 py-3"><div class="rounded-xl bg-emerald-50 p-2 text-emerald-700"><HandCoins :size="18"/></div><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold">{{item.external_id}}</p><p class="text-xs text-slate-400">{{new Date(item.paid_at).toLocaleString('pt-BR')}} · {{item.payment_method}}</p></div><strong class="text-emerald-700">{{money(item.amount)}}</strong></div><p v-if="!recentPayments.length" class="py-10 text-center text-sm text-slate-400">Nenhum pagamento.</p></div></section></div></template>
