<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Edit3, Plus, RefreshCw, Trash2 } from 'lucide-vue-next'
import { api, apiError } from '../api/client';import type { ApiResponse } from '../types'
import PageHeader from '../components/PageHeader.vue';import DrawerPanel from '../components/DrawerPanel.vue';import InlineAlert from '../components/InlineAlert.vue';import StatusBadge from '../components/StatusBadge.vue';import EmptyState from '../components/EmptyState.vue'
interface Role{id:string;code:string;name:string;description?:string;permissions:string[];is_system:boolean;is_active:boolean;created_at:string}
const items=ref<Role[]>([]),presets=ref<Record<string,string[]>>({}),drawer=ref(false),editing=ref<Role|null>(null),error=ref(''),success=ref('')
const form=reactive({code:'',name:'',description:'',permissions:'',is_active:true})
async function load(){try{const [r,p]=await Promise.all([api.get<ApiResponse<Role[]>>('/v1/roles'),api.get<ApiResponse<Record<string,string[]>>>('/v1/role-presets')]);items.value=r.data.data;presets.value=p.data.data}catch(e){error.value=apiError(e)}}
function open(item?:Role){editing.value=item||null;Object.assign(form,item?{code:item.code,name:item.name,description:item.description||'',permissions:item.permissions.join('\n'),is_active:item.is_active}:{code:'',name:'',description:'',permissions:'',is_active:true});drawer.value=true}
function applyPreset(code:string){const permissions=presets.value[code]||[];form.permissions=permissions.join('\n');if(!editing.value){form.code=code;form.name=code.split('_').map(v=>v[0]+v.slice(1).toLowerCase()).join(' ')}}
async function save(){try{const payload={code:form.code,name:form.name,description:form.description||null,permissions:form.permissions.split(/[\n,]/).map(v=>v.trim()).filter(Boolean),is_active:form.is_active};if(editing.value)await api.patch(`/v1/roles/${editing.value.id}`,payload);else await api.post('/v1/roles',payload);drawer.value=false;success.value='Perfil salvo.';await load()}catch(e){error.value=apiError(e)}}
async function remove(item:Role){if(!confirm(`${item.is_system?'Desativar':'Excluir'} ${item.name}?`))return;try{await api.delete(`/v1/roles/${item.id}`);await load()}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>
<template><PageHeader title="Perfis e permissões" subtitle="RBAC granular do tenant e acesso separado por empresa."><button class="btn-secondary" @click="load"><RefreshCw :size="18"/>Atualizar</button><button class="btn-primary" @click="open()"><Plus :size="18"/>Novo perfil</button></PageHeader><InlineAlert :message="error" @dismiss="error=''"/><InlineAlert :message="success" type="success" @dismiss="success=''"/><div class="grid gap-5 xl:grid-cols-2"><article v-for="item in items" :key="item.id" class="card"><div class="flex items-start gap-3"><div class="flex-1"><div class="flex items-center gap-2"><h2 class="font-bold">{{item.name}}</h2><span class="badge bg-slate-100 text-slate-700">{{item.code}}</span><span v-if="item.is_system" class="badge bg-violet-50 text-violet-700">Sistema</span><StatusBadge :status="item.is_active?'ACTIVE':'INACTIVE'"/></div><p class="mt-2 text-sm text-slate-500">{{item.description||'Sem descrição'}}</p></div><button class="btn-secondary px-3 py-2" @click="open(item)"><Edit3 :size="16"/></button><button class="btn-secondary px-3 py-2 text-rose-600" @click="remove(item)"><Trash2 :size="16"/></button></div><div class="mt-4 flex max-h-28 flex-wrap gap-1 overflow-auto"><span v-for="p in item.permissions" :key="p" class="badge bg-teal-50 text-teal-700">{{p}}</span></div></article><EmptyState v-if="!items.length" title="Nenhum perfil cadastrado"/></div><DrawerPanel :open="drawer" :title="editing?'Editar perfil':'Novo perfil'" width="xl" @close="drawer=false"><form class="grid gap-4 md:grid-cols-2" @submit.prevent="save"><div><label class="label">Código</label><input v-model="form.code" class="input uppercase" :disabled="!!editing?.is_system" required/></div><div><label class="label">Nome</label><input v-model="form.name" class="input" required/></div><div class="md:col-span-2"><label class="label">Descrição</label><textarea v-model="form.description" class="input" rows="2"/></div><div class="md:col-span-2"><label class="label">Aplicar preset</label><div class="flex flex-wrap gap-2"><button v-for="(_,code) in presets" :key="String(code)" type="button" class="btn-secondary px-3 py-2" @click="applyPreset(String(code))">{{code}}</button></div></div><div class="md:col-span-2"><label class="label">Permissões, uma por linha</label><textarea v-model="form.permissions" class="input font-mono text-xs" rows="14"/></div><label class="flex gap-2 text-sm"><input v-model="form.is_active" type="checkbox"/>Perfil ativo</label><div class="md:col-span-2 flex justify-end gap-2 border-t pt-4"><button type="button" class="btn-secondary" @click="drawer=false">Cancelar</button><button class="btn-primary">Salvar</button></div></form></DrawerPanel></template>
