<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Edit3, Plus, RefreshCw } from 'lucide-vue-next'
import { api, apiError } from '../api/client';import type { ApiResponse, ServiceItem } from '../types'
import PageHeader from '../components/PageHeader.vue';import DrawerPanel from '../components/DrawerPanel.vue';import InlineAlert from '../components/InlineAlert.vue';import StatusBadge from '../components/StatusBadge.vue';import EmptyState from '../components/EmptyState.vue';import JsonEditor from '../components/JsonEditor.vue'
const items=ref<ServiceItem[]>([]),drawer=ref(false),editing=ref<ServiceItem|null>(null),error=ref(''),success=ref('')
const form=reactive({code:'',name:'',description:'',default_amount:'0',default_frequency:'MONTHLY',fiscal_service_code:'',settings:'{}',is_active:true})
const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
async function load(){try{items.value=(await api.get<ApiResponse<ServiceItem[]>>('/v1/services')).data.data}catch(e){error.value=apiError(e)}}
function open(item?:ServiceItem&{fiscal_service_code?:string;settings?:Record<string,unknown>}){editing.value=item||null;Object.assign(form,item?{code:item.code,name:item.name,description:item.description||'',default_amount:item.default_amount,default_frequency:item.default_frequency,fiscal_service_code:item.fiscal_service_code||'',settings:JSON.stringify(item.settings||{},null,2),is_active:item.is_active}:{code:'',name:'',description:'',default_amount:'0',default_frequency:'MONTHLY',fiscal_service_code:'',settings:'{}',is_active:true});drawer.value=true}
async function save(){try{const payload={...form,default_amount:Number(form.default_amount),settings:JSON.parse(form.settings)};if(editing.value)await api.patch(`/v1/services/${editing.value.id}`,payload);else await api.post('/v1/services',payload);drawer.value=false;success.value='Serviço salvo.';await load()}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>
<template><PageHeader title="Serviços e produtos" subtitle="Catálogo utilizado pelos contratos, recorrências e emissão fiscal."><button class="btn-secondary" @click="load"><RefreshCw :size="18"/>Atualizar</button><button class="btn-primary" @click="open()"><Plus :size="18"/>Novo serviço</button></PageHeader><InlineAlert :message="error" @dismiss="error=''"/><InlineAlert :message="success" type="success" @dismiss="success=''"/><div class="grid gap-4 xl:grid-cols-3"><article v-for="item in items" :key="item.id" class="card"><div class="flex items-start gap-3"><div class="flex-1"><p class="text-xs font-semibold uppercase tracking-wide text-teal-700">{{item.code}}</p><h2 class="mt-1 font-bold">{{item.name}}</h2><p class="mt-2 line-clamp-2 text-sm text-slate-500">{{item.description||'Sem descrição'}}</p></div><button class="btn-secondary px-3 py-2" @click="open(item)"><Edit3 :size="16"/></button></div><div class="mt-5 flex items-end justify-between border-t border-slate-100 pt-4"><div><p class="text-xs text-slate-400">Valor padrão</p><p class="text-lg font-bold">{{money(item.default_amount)}}</p></div><div class="text-right"><p class="text-xs text-slate-400">Periodicidade</p><p class="text-sm font-semibold">{{item.default_frequency}}</p></div><StatusBadge :status="item.is_active?'ACTIVE':'INACTIVE'"/></div></article><EmptyState v-if="!items.length" title="Nenhum serviço cadastrado"/></div><DrawerPanel :open="drawer" :title="editing?'Editar serviço':'Novo serviço'" width="lg" @close="drawer=false"><form class="grid gap-4 md:grid-cols-2" @submit.prevent="save"><div><label class="label">Código</label><input v-model="form.code" class="input uppercase" :disabled="!!editing" required/></div><div><label class="label">Nome</label><input v-model="form.name" class="input" required/></div><div class="md:col-span-2"><label class="label">Descrição</label><textarea v-model="form.description" class="input" rows="3"/></div><div><label class="label">Valor padrão</label><input v-model="form.default_amount" type="number" min="0" step="0.01" class="input"/></div><div><label class="label">Periodicidade</label><select v-model="form.default_frequency" class="select"><option>MONTHLY</option><option>WEEKLY</option><option>BIWEEKLY</option><option>QUARTERLY</option><option>SEMIANNUALLY</option><option>ANNUALLY</option><option>CUSTOM</option></select></div><div><label class="label">Código fiscal do serviço</label><input v-model="form.fiscal_service_code" class="input"/></div><label class="flex items-end gap-2 pb-3 text-sm"><input v-model="form.is_active" type="checkbox"/>Serviço ativo</label><JsonEditor v-model="form.settings" label="Configurações adicionais"/><div class="md:col-span-2 flex justify-end gap-2 border-t pt-4"><button type="button" class="btn-secondary" @click="drawer=false">Cancelar</button><button class="btn-primary">Salvar</button></div></form></DrawerPanel></template>
