<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { KeyRound, Plus, Save, Shield, UserCog } from 'lucide-vue-next'
import { api, apiError } from '../api/client'
import type { ApiResponse, Company } from '../types'
import PageHeader from '../components/PageHeader.vue'
import ModalDialog from '../components/ModalDialog.vue'
import StatusBadge from '../components/StatusBadge.vue'

interface TenantUser { id:string;name:string;email:string;phone?:string|null;role:string;permissions:string[];companies:string[];is_active:boolean;last_login_at?:string|null;created_at:string }
const users=ref<TenantUser[]>([]);const companies=ref<Company[]>([]);const presets=ref<Record<string,string[]>>({});const error=ref('');const success=ref('');const modal=ref<'create'|'edit'|'password'|''>('');const selected=ref<TenantUser|null>(null)
const form=reactive({name:'',email:'',phone:'',password:'',role:'FINANCE_OPERATOR',permissions:[] as string[],company_ids:[] as string[],is_active:true})
const roleNames:Record<string,string>={TENANT_ADMIN:'Administrador do tenant',FINANCE_MANAGER:'Gestor financeiro',FINANCE_OPERATOR:'Operador financeiro',COLLECTION_OPERATOR:'Operador de cobrança',TREASURY:'Tesouraria',FISCAL:'Fiscal',AUDITOR:'Auditor',VIEWER:'Consulta'}
const allPermissions=computed(()=>Array.from(new Set(Object.values(presets.value).flat())).sort())
const companyName=(id:string)=>companies.value.find(c=>c.id===id)?.trade_name||companies.value.find(c=>c.id===id)?.legal_name||id
async function load(){error.value='';try{const [u,c,p]=await Promise.all([api.get<ApiResponse<TenantUser[]>>('/v1/users'),api.get<ApiResponse<Company[]>>('/v1/companies'),api.get<ApiResponse<Record<string,string[]>>>('/v1/role-presets')]);users.value=u.data.data;companies.value=c.data.data;presets.value=p.data.data}catch(e){error.value=apiError(e)}}
function applyPreset(){form.permissions=[...(presets.value[form.role]||[])]}
function openCreate(){selected.value=null;Object.assign(form,{name:'',email:'',phone:'',password:'',role:'FINANCE_OPERATOR',permissions:[...(presets.value.FINANCE_OPERATOR||[])],company_ids:companies.value.map(c=>c.id),is_active:true});modal.value='create'}
function openEdit(item:TenantUser){selected.value=item;Object.assign(form,{name:item.name,email:item.email,phone:item.phone||'',password:'',role:item.role,permissions:[...item.permissions],company_ids:[...item.companies],is_active:item.is_active});modal.value='edit'}
async function save(){error.value='';try{if(modal.value==='create'){await api.post('/v1/users',form);success.value='Usuário criado com sucesso.'}else if(selected.value){await api.patch(`/v1/users/${selected.value.id}`,{name:form.name,phone:form.phone||null,role:form.role,permissions:form.permissions,company_ids:form.company_ids,is_active:form.is_active});success.value='Usuário atualizado.'}modal.value='';await load()}catch(e){error.value=apiError(e)}}
function openPassword(item:TenantUser){selected.value=item;form.password='';modal.value='password'}
async function resetPassword(){if(!selected.value)return;error.value='';try{await api.post(`/v1/users/${selected.value.id}/password`,{password:form.password});success.value='Senha redefinida e sessões anteriores revogadas.';modal.value=''}catch(e){error.value=apiError(e)}}
onMounted(load)
</script>
<template>
<PageHeader title="Usuários e permissões" subtitle="Acesso isolado por tenant, empresas e permissões granulares."><button class="btn-primary" @click="openCreate"><Plus :size="18"/> Novo usuário</button></PageHeader>
<p v-if="error" class="mb-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{{error}}</p><p v-if="success" class="mb-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{{success}}</p>
<div class="grid gap-4 xl:grid-cols-2"><article v-for="item in users" :key="item.id" class="card"><div class="flex items-start gap-4"><div class="rounded-2xl bg-slate-100 p-3 text-slate-700"><UserCog :size="24"/></div><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center justify-between gap-2"><div><p class="font-bold text-slate-900">{{item.name}}</p><p class="text-sm text-slate-500">{{item.email}}</p></div><StatusBadge :status="item.is_active?'ACTIVE':'DISABLED'"/></div><p class="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-teal-700"><Shield :size="16"/> {{roleNames[item.role]||item.role}}</p><div class="mt-3 flex flex-wrap gap-1"><span v-for="company in item.companies" :key="company" class="badge bg-slate-100 text-slate-600">{{companyName(company)}}</span><span v-if="!item.companies.length" class="text-xs text-slate-400">Sem empresas específicas</span></div><p class="mt-3 text-xs text-slate-400">Último acesso: {{item.last_login_at?new Date(item.last_login_at).toLocaleString('pt-BR'):'Nunca'}}</p><div class="mt-4 flex gap-2"><button class="btn-secondary !px-3 !py-2" @click="openEdit(item)"><Save :size="16"/> Editar</button><button class="btn-secondary !px-3 !py-2" @click="openPassword(item)"><KeyRound :size="16"/> Senha</button></div></div></div></article></div>
<ModalDialog :open="modal==='create'||modal==='edit'" :title="modal==='create'?'Novo usuário':'Editar usuário'" size="xl" @close="modal='' "><form class="space-y-5" @submit.prevent="save"><div class="grid gap-4 md:grid-cols-2"><div><label class="label">Nome</label><input v-model="form.name" class="input" required/></div><div><label class="label">E-mail</label><input v-model="form.email" type="email" class="input" required :disabled="modal==='edit'"/></div><div><label class="label">Telefone</label><input v-model="form.phone" class="input"/></div><div v-if="modal==='create'"><label class="label">Senha inicial</label><input v-model="form.password" type="password" minlength="12" class="input" required autocomplete="new-password"/></div><div><label class="label">Papel</label><select v-model="form.role" class="select" @change="applyPreset"><option v-for="(_,role) in presets" :key="role" :value="role">{{roleNames[role]||role}}</option></select></div><label class="flex items-center gap-2 pt-8 text-sm"><input v-model="form.is_active" type="checkbox"/> Usuário ativo</label></div><div><label class="label">Empresas permitidas</label><div class="grid gap-2 rounded-xl border border-slate-200 p-3 sm:grid-cols-2"><label v-for="company in companies" :key="company.id" class="flex items-center gap-2 text-sm"><input v-model="form.company_ids" type="checkbox" :value="company.id"/> {{company.trade_name||company.legal_name}}</label></div></div><details class="rounded-xl border border-slate-200 p-4"><summary class="cursor-pointer font-semibold text-slate-700">Permissões granulares ({{form.permissions.length}})</summary><div class="mt-4 grid max-h-64 gap-2 overflow-auto sm:grid-cols-2 lg:grid-cols-3"><label v-for="permission in allPermissions" :key="permission" class="flex items-center gap-2 text-xs"><input v-model="form.permissions" type="checkbox" :value="permission"/> {{permission}}</label></div></details><div class="flex justify-end gap-2"><button type="button" class="btn-secondary" @click="modal=''">Cancelar</button><button class="btn-primary"><Save :size="18"/> Salvar</button></div></form></ModalDialog>
<ModalDialog :open="modal==='password'" title="Redefinir senha" @close="modal='' "><form class="space-y-4" @submit.prevent="resetPassword"><p class="text-sm text-slate-500">A nova senha será aplicada a {{selected?.name}} e todos os refresh tokens atuais serão revogados.</p><div><label class="label">Nova senha</label><input v-model="form.password" type="password" minlength="12" class="input" required autocomplete="new-password"/></div><div class="flex justify-end gap-2"><button type="button" class="btn-secondary" @click="modal=''">Cancelar</button><button class="btn-primary"><KeyRound :size="18"/> Redefinir</button></div></form></ModalDialog>
</template>
